export const VERIFY_ACCESS_STARTED = 'VERIFY_ACCESS_STARTED';
export const VERIFY_ACCESS_END = 'VERIFY_ACCESS_END';

export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

export const PLAY_GAME_STARTED = 'PLAY_GAME_STARTED';
export const PLAY_GAME_FAILURE = 'PLAY_GAME_FAILURE';
export const PLAY_GAME_SUCCESS = 'PLAY_GAME_SUCCESS';

export const END_GAME_FAILURE = 'END_GAME_FAILURE';
export const END_GAME_SUCCESS = 'END_GAME_SUCCESS';
